services:
  backend:
    image: debgain/blog-projects-backend:latest
    container_name: backend
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      CORS_ORIGINS: ${CORS_ORIGINS}
    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('http').get('http://localhost:5000/_dbhealth',r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))\""]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: debgain/blog-projects-frontend:latest
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy

